### ISSUE TITLE
How do I get the E-mail Adressen instand of Name 

### ISSUE THREAD

**Issue by Jade2508** [noSpamProxy/Reports#3]
How do I get the E-mail Adresses of each user instead of the Name in Get-NspLicenseReport.ps1. What Command do I have you use Instad of $user.DisplayName?

**Comment by janjaeschke** [comment]
@Jade2508 excuse me for the late response. 

It is not possible to get the E-mail Addresses using Get-NspLicenseReport.ps1.
This is caused by the used Get-NspFeatureUsage CmdLet.

If you use the Get-NspLicenseReport_(Database) report you could tweak the SQL query to get E-mail Addresses only.
You need to remove u.Displayname and the COALESCE statement.
In detail:
line 4:
		COALESCE (u.Displayname, s.Address) AS DisplayName, 
becomes
		s.Address AS DisplayName, 

line 14:
              GROUP BY COALESCE (u.Displayname, s.Address), s.Domain
becomes
              GROUP BY s.Address, s.Domain
